id = "rue"
name = "Rue"
description = "Ruby Single File Component support for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Your Name <your.email@example.com>"]
repository = "https://github.com/delano/zed-rue"

[grammars.rue]
repository = "https://github.com/delano/tree-sitter-rue"
commit = "767431544e4bdd35e620cc545d6744e671b4e54c"
path = "tree-sitter-rue"
