id = "rue"
name = "Rue"
description = "Ruby Single File Component support for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Your Name <your.email@example.com>"]
repository = "https://github.com/yourusername/zed-rue"

[grammars.rue]
repository = "https://github.com/yourusername/tree-sitter-rue"
commit = "main"  # Will need to update once grammar is published
